### ISSUE TITLE
如下引用的GameDefine.js在哪里？可以发上来吗？不然没法用

### ISSUE THREAD

**Issue by andynicoo** [glegoo/cocos-creator-level-editor#1]
let GameDefine = require('../../temp/quick-scripts/assets/script/GameDefine.js').GameDefine
let NodeType = require('../../temp/quick-scripts/assets/script/GameDefine.js').NodeType

**Comment by glegoo** [comment]
这个项目并非打开即用的，主要是分享如何把prefab转为JSON, 和如何根据JSON生成prefab的流程，项目代码为公司所有，不方便公开。

**Comment by andynicoo** [comment]
> 这个项目并非打开即用的，主要是分享如何把prefab转为JSON, 和如何根据JSON生成prefab的流程，项目代码为公司所有，不方便公开。

好的，我仔细看了下，里面的游戏逻辑需要自行修改，谢谢提供的思路
